---
- name: Initialisation 
  hosts: WEB
  remote_user: root
  tasks:
  - name: Enable HA
    shell: dnf config-manager --set-enabled HighAvailability
    args:
      executable: /bin/bash        
  - name: Install Pacemaker
    dnf:
      name:
        - pcs
        - pacemaker
        - fence-agents-common
  - name: Configuration du jeton
    shell: echo "grp1" | passwd hacluster --stdin 
    args:
      executable: /bin/bash
  - name: Activation du service pcsd
    shell: systemctl enable pcsd --now
    args:
      executable: /bin/bash
  - name: Configuration DNS
    copy:
      src: /home/grp1/ansible-infra/configuration-file/WEB/hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: u=rw,g=r,o=r
  - name: Allow Cluster in iptables
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 2224
      jump: ACCEPT
      action: insert
  - name: Allow rules cluster
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 3121
      jump: ACCEPT
      action: insert
  - name: Allow rules cluster
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 5403
      jump: ACCEPT
      action: insert
  - name: Allow rules cluster
    iptables:
      chain: INPUT
      protocol: udp
      destination_port: 5404
      jump: ACCEPT
      action: insert
  - name: Allow rules cluster
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 9929
      jump: ACCEPT
      action: insert
  - name: Allow rules cluster
    iptables:
      chain: INPUT
      protocol: udp
      destination_port: 9929
      jump: ACCEPT
      action: insert
  - name: Allow rules cluster
    iptables:
      chain: INPUT
      protocol: udp
      destination_port: 21064
      jump: ACCEPT
      action: insert
  - name: save iptables
    shell: iptables-save > /etc/sysconfig/iptables
    args:
      executable: /bin/bash
  - name: Restart iptables
    service:
      name: iptables
      state: restarted


- name: Configuration pcs sur WEB1
  hosts: WEB1
  remote_user: root
  tasks:
  - name: Configuration de pcs
    shell: pcs host auth -u hacluster -p grp1 glpi-1 glpi-2
    args:
      executable: /bin/bash
  - name: Creation du cluster
    shell: pcs cluster setup --start Apache_cluster glpi-1 glpi-2
    args:
      executable: /bin/bash


- name: Activations des nodes
  hosts: WEB
  remote_user: root
  tasks:
  - name: Activation du cluster hacluster
    shell: pcs cluster enable --all
    args:
      executable: /bin/bash

- name: COnfiguration de l'IP virtuelle
  hosts: WEB1
  remote_user: root
  tasks:
  - name: Disable stonith
    shell: pcs property set stonith-enabled=false
    args:
      executable: /bin/bash
  - name: Activation de l'IP virtuelle
    shell: pcs resource create Apache_vip ocf:heartbeat:IPaddr2 ip=192.168.20.50 cidr_netmask=24 --group Apache_Grp
    args:
      executable: /bin/bash
  - name: Ajout du service Apache au cluster
    shell: pcs resource create apache_ser service:httpd --group Apache_Grp
    args:
      executable: /bin/bash
