---
- name: Install GLPI
  hosts: TEST
  remote_user: root
  vars:
    mysql_root_password: "grp1"
  tasks:
  - name: install mariadb
    yum:
      name:
        - mariadb-server
        - python3-PyMySQL
      state: latest
  - name: ensure that Mariadb is started
    service:
      name: mariadb
      state: started
  - name: update mysql root password for all root accounts
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
  - name: Copy the root credentials as .my.cnf file
    template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
  - name: Create a New Test DB called MyNewDB
    mysql_db: name=MyNewDB state=present login_user=root login_password={{ mysql_root_password }}

#  - name: update mysql root password for all root accounts
#    mysql_user:
#      name: root
#      password: "{{ mysql_root_password }}"
#      login_user: root
#      login_password: "{{ mysql_root_password }}"
#      check_implicit_admin: yes
#      priv: "*.*:ALL,GRANT"
#  - name: Create a new database with name 'bobdata'
#    mysql_db:
#      name: bobdata
#      state: present


