---
- name: Install GLPI
  hosts: DB
  remote_user: grp1
  vars:
    mysql_root_password: "grp1"
  tasks:
  - name: Copy the root credentials as .my.cnf file
    template: src=mariadb-servermaster.cnf dest=/etc/my.cnf.d/mariadb-server.cnf
    become: yes
    become_method: sudo
    when: inventory_hostname == "SRV-DB1"
  - name: Copy the root credentials as .my.cnf file
    template: src=mariadb-serverslave.cnf dest=/etc/my.cnf.d/mariadb-server.cnf
    become: yes
    become_method: sudo
    when: inventory_hostname == "SRV-DB2"

  - name: restart mariadb *2
    shell: systemctl restart mariadb 
    args:
      executable: /bin/bash
    become: yes
    become_method: sudo

  - block:
     - name: run backup
       shell: mariabackup --backup --target-dir mariabk -u root -p grp1
       args:
         executable: /bin/bash
       become: yes
       become_method: sudo

     - name: run tar 
       shell: tar -cvf bk.tar mariabk
       args:
         warn : false
         executable: /bin/bash
       become: yes
       become_method: sudo

     - name: run transfert
       shell: scp bk.tar root@192.168.20.24:/home/grp1/.
       args:
         executable: /bin/bash
       become: yes
       become_method: sudo

    when: inventory_hostname == "SRV-DB1"

  - block:
     - name: stop mariadb
       shell: systemctl stop mariadb
       args:
         executable: /bin/bash
       become: yes
       become_method: sudo

     - name: run decom
       shell: tar -xvf "bk.tar"
       args:
          warn: false
          executable: /bin/bash
       become: yes
       become_method: sudo

     - name: delete file in /var/lib/mysql/*
       shell: rm -rf /var/lib/mysql/*
       args:
          warn: false
          executable: /bin/bash
       become: yes
       become_method: sudo

     - name: run prepare restore
       shell: mariabackup --prepare --target-dir mariabk
       args:
          warn: false
          executable: /bin/bash
       become: yes
       become_method: sudo

     - name: run restore
       shell: mariabackup --copy-back --target-dir mariabk
       args:
          warn: false
          executable: /bin/bash
       become: yes
       become_method: sudo

     - name: run restore
       shell: chown -R mysql:mysql /var/lib/mysql/
       args:
          warn: false
          executable: /bin/bash
       become: yes
       become_method: sudo

     - name: start mariadb
       shell: systemctl start mariadb
       args: 
         executable: /bin/bash
       become: yes
       become_method: sudo

     - name: Change master information in slave 
       mysql_replication:
         login_user: root
         login_password: grp1
         mode: changemaster
         master_host: 192.168.20.23
         master_user: root
         master_password: grp1
         master_log_file: mysql-bin.000001
         master_log_pos: 328
     - name: Start slave1
       mysql_replication:
        mode: startslave
        login_user: root
        login_password: grp1



    when: inventory_hostname == "SRV-DB2"

  - block:
     - name: Copie de la base glpi
       copy:
         src: /home/grp1/ansible-infra/configuration-file/GLPI/glpidb.sql
         dest: /home/grp1/glpidb.sql
         owner: grp1
         group: grp1
         mode: u=rw,g=rw,o=r
     - name: Chargement de la base GLPI
       shell: mysql --user=root --password=grp1 glpidb < /home/grp1/glpidb.sql
       args:
         executable: /bin/bash
    when: inventory_hostname == "SRV-DB1"  
 # - block:

#      - name: test
#        copy:
#          src: /home/grp1/ansible-infra/configuration-file/bck_bd1
#          dest: /home/grp1/
#          owner: root
#          group: root
#          mode: u=rw,g=r,o=r
#      - name: transfert database glpi ok
#        shell: scp /home/grp1/ansible-infra/bck_bd1  root@192.168.20.23:/home/grp1 
#        args:
#         executable: /bin/bash
#      - name: restart mariadb *2
#        shell: mysqldump -u root -pgrp1 glpidb < /home/grp1/bck_bd1 
#        args:
#         executable: /bin/bash

#    when: inventory_hostname == "SRV-DB1"
 

#     - name: run backup 
#       shell: systemctl stop  mariadb 
#       args:
#         executable: /bin/bash

#     - name: run backup 
#       shell: systemctl stop  mariadb 
#       args:
#         executable: /bin/bash


