
- name: Install GLPI
  hosts: DB
  remote_user: root
  tasks:
  - name: Change master to master server 192.0.2.1 and use binary log 'mysql-bin.000009' with position 4578
    mysql_replication:
      login_user: root
      login_password: grp1
      mode: changemaster
      master_host: 192.168.20.23
      master_user: root
      master_password: grp1
      master_log_file: mysql-bin.000001
      master_log_pos: 328
    when: inventory_hostname == "SRV-DB2"
    
  - name: Start MariaDB standby with connection name master-1
    mysql_replication:
      mode: startslave
      login_user: root
      login_password: grp1
    when: inventory_hostname == "SRV-DB2"
    
